export const signupConstant = {
    SIGNUP_FAILURE:'SIGNUP_FAILURE',
    SIGNUP_SUCCESS:'SIGNUP_SUCCESS',
    SIGNUP_REQUIEST:'SIGNUP_REQUIEST'
}

export const loginConstant = {
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_REQUIEST:'LOGIN_REQUIEST'
}

export const logoutConstatnt = {
    USER_LOGOUT_FAILURE:'USER_LOGOUT_FAILURE',
    USER_LOGOUT_SUCCESS:'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_REQUIEST:'USER_LOGOUT_REQUIEST'
}

export const autoLoginConstant = {
    AUTO_AUTH_FAILURE:'AUTO_AUTH_FAILURE',
    AUTO_AUTH_SUCCESS:'AUTO_AUTH_SUCCESS',
    AUTO_AUTH_REQUIEST:'AUTO_AUTH_REQUIEST'
}

export const updateProfileConstant = {
    UPDATE_PROFILE_REQUIEST:'UPDATE_PROFILE_REQUIEST',
    UPDATE_PROFILE_FAILURE:'UPDATE_PROFILE_FAILURE',
    UPDATE_PROFILE_SUCCESS:'UPDATE_PROFILE_SUCCESS',
}

export const profileInfoConstant = {
    GET_PROFILE_REQUIEST:'GET_PROFILE_REQUIEST',
    GET_PROFILE_FAILURE:'GET_PROFILE_FAILURE',
    GET_PROFILE_SUCCESS:'GET_PROFILE_SUCCESS',
}


export const avatarConstant = {
    SET_AVATAR_FAILURE:'SET_AVATAR_FAILURE',
    SET_AVATAR_SUCCESS:'SET_AVATAR_SUCCESS',
    SET_AVATAR_REQUIEST:'SET_AVATAR_REQUIEST'
}


export const uploadFileConstant = {
    UPLOAD_FILE_FAILURE:'UPLOAD_FILE_FAILURE',
    UPLOAD_FILE_SUCCESS:'UPLOAD_FILE_SUCCESS',
    UPLOAD_FILE_REQUIEST:'UPLOAD_FILE_REQUIEST'
}

export const GenLinkFileConstant = {
    GENlINK_FILE_FAILURE:'GENlINK_FILE_FAILURE',
    GENlINK_FILE_SUCCESS:'GENlINK_FILE_SUCCESS',
    GENlINK_FILE_REQUIEST:'GENlINK_FILE_REQUIEST'
}

export const DashboardConstant = {
    DASHBOARD_FAILURE:'DASHBOARD_FAILURE',
    DASHBOARD_SUCCESS:'DASHBOARD_SUCCESS',
    DASHBOARD_REQUIEST:'DASHBOARD_REQUIEST'
}


